
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: MXHSV
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3309:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: MXHSV
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend  # Đường dẫn đến thư mục frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge